### ISSUE TITLE
ERROR: The config profile (eb-cli) could not be found

### ISSUE THREAD

**Issue by kuriel-trivu** [mini-containers/eb-cli#1]
I have this gitlab-ci.yml

```
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.aws
    - touch ~/.aws/config
    - chmod 600 ~/.aws/config
    - echo "[profile eb-cli]" >> ~/.aws/config
    - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/config
    - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
    - git checkout $CI_COMMIT_REF_NAME
    - git fetch --all
    - git pull
    - docker run -i -v $PWD:/data -v ~/.aws:/home/aws/.aws --rm mini/eb-cli labs cleanup-versions --force
    - docker run -i -v $PWD:/data -v ~/.aws:/home/aws/.aws --rm mini/eb-cli deploy
    - docker rm $(docker ps -a -q)
    - docker ps -a
    - echo "DEPLOYMENT OF $CI_COMMIT_REF_NAME IS COMPLETE"
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - dev
    - master
```
